Car.create(name: 'Toyota', 
car_type: '4-wheel derive', 
make:'HINO',
description: "Toyota Motor Corp., Largest Japanese automobile manufacturer and one of the largest automotive companies in the world. It was established in 1933 as a division of the Toyoda Automatic Loom Works, Ltd., and in",
images: { White: 'https://www.auto-data.net/en/ac-ace-generation-1#image3',
dark: 'https://www.auto-data.net/en/ac-ace-generation-1#image3'}, 
cost: 100.00,
speed:  70,
color: ['White', 'dark', 'red'],
)